author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2022-01-01
description = Impute missing values by some method
tags = C13 C52
min-version = 2021d
public = impute impute_by_sts first last
help = Imputer_help.txt
sample-script = Imputer_sample.inp
depends = extra PanelTools StrucTiSM
# provider = PanelTools
