author = Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2023-02-05
description = Impute missing values by some method
tags = C13 C52
min-version = 2021d
public = first impute impute_by_sts last mode
help = Imputer_help.txt
sample-script = Imputer_sample.inp
depends = extra PanelTools StrucTiSM
# provider = PanelTools
